### PR TITLE
Enhance password checking, logging and rejecting

### LINKED ISSUE #810: [1.8.4] password is limited to 16 characters
This was also valid for 1.6.x and is not mentioned anywhere (not in docs or during chpass). Password is just cut to the first 16 characters.
```
.+user testpass
.chpass testpass 123456789012345678

.tcl passwdok testpass 123456789012345
Tcl: 0
.tcl passwdok testpass 1234567890123456
Tcl: 1
.tcl passwdok testpass 1234567890123457
Tcl: 0
.tcl passwdok testpass 12345678901234567
Tcl: 0
.tcl passwdok testpass 123456789012345678
Tcl: 0
```
This also happens for `/msg op` resulting with "failed OP" for valid password.

The cause of this lies in:
```
static void cmd_chpass(struct userrec *u, int idx, char *par)
[...]
      l = strlen(new = newsplit(&par));
      if (l > 16)
        new[16] = 0; 
```

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: wilkowy
Patch by: michaelortmann
Fixes: #810 

One-line summary:
Enhance password len checking, logging, rejecting (instead of truncating)

Additional description (if needed):
1. The upper limit for password length within eggdrop was never consistent, like /msg cutted to 15 chars, chpass to 16 chars.
2. Unify with commit 103128c93f31bb09bb0a8149cc1dac51f5625858
3. Later, #906 will probably lift the upper limit to password length, which will be easier, once this PR unified password length handling.
4. Fixed return codes in msgcmds.c:msg_pass() (was not really broken, but hey ;)
5. Eggdrop distinguishes plain from encrypted passwords (in pass_set()) with first char == '+'. At the same time it allows users to enter such + passwords. Those would not only end up as plain text in userfile, but would also forbid the user to use it / login. This PR fixes this. It rejects such + passwds, see test case below.
6. Less code doubling by using a new common function. Sadly, it cant be used for /msg also, because of the different logging/noticing.

Test cases demonstrating functionality (if applicable):
**Test 1 - + password - Before**
```
Before:

.chpass testuser +12345
Changed password.

Userfile:
testuser   - hp
--PASS +12345
--XTRA created 1585178624

$ telnet 127.0.0.1 3333
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.


Nickname.
testuser

Enter your password.
Negative on that, Houston.
Connection closed by foreign host.
```
**Test 1 - Partyline - After**
```
.chpass testuser 12345
[02:59:06] tcl: builtin dcc call: *dcc:chpass -HQ 1 [something]
Please use at least 6 characters.
.chpass testuser 123456
[02:59:11] tcl: builtin dcc call: *dcc:chpass -HQ 1 [something]
[02:59:11] #-HQ# chpass testuser [something]
Changed password.
.chpass testuser 123456789012345
[02:59:16] tcl: builtin dcc call: *dcc:chpass -HQ 1 [something]
[02:59:16] #-HQ# chpass testuser [something]
Changed password.
.chpass testuser 1234567890123456
[02:59:17] tcl: builtin dcc call: *dcc:chpass -HQ 1 [something]
Please use at most 15 characters.
.chpass testuser +12345
[02:59:22] tcl: builtin dcc call: *dcc:chpass -HQ 1 [something]
Please do not use + as first character.
```
**Test 2 - /msg - After**
```
-> *BotA* pass oldpass 12345
-BotA- Please use at least 6 characters.
-> *BotA* pass oldpass 123456
-BotA- Password changed to: '123456'.
-> *BotA* pass 123456 123456789012345
-BotA- Password changed to: '123456789012345'.
-> *BotA* pass 123456789012345 1234567890123456
-> *BotA* pass 123456789012345 +12345
-BotA- Please do not use + as first character.
```

### CODE REVIEW

**Comment by vanosg** [comment]
I'm not a fan of changing the password to something the user didn't explicitly set, I rather prefer rejecting it and making them re-do it. Is there a reason to change this behavior? Also, can you help me understand the rationale for removing the check for 6 characters as a minimum? Thanks

**Comment by michaelortmann** [comment]
Ready for review.

**Comment by michaelortmann** [comment]
Ready for review.

**Comment by vanosg** [comment]
Tests for most recent push:
```
# Exercising all check_validpass() paths
.newpass +123456
Password cannot start with '+', please try again.
.newpass 123
Please use at least 6 characters.
.newpass 1234567891123456789212345678931234567894
Passwords cannot be longer than 15 characters, please try again.

# Works with .chpass
.chpass foo +123456
Password cannot start with '+', please try again.

# Works with /msg
/msg Eggdrop PASS oldpass +12345678
23:39 -- MSG(Eggdrop): pass getegg +12345678
23:39 -- BeerBot (*!*@*): Password cannot start with '+', please try again
```

**Comment by michaelortmann** [comment]
Developer test .chpass and .newpass:
```
.chpass testuser 12345
Please use at least 6 characters.
.chpass testuser 123456
Changed password.
.chpass testuser 123456789012345
Changed password.
.chpass testuser 1234567890123456
Passwords cannot be longer than 15 characters, please try again.
.chpass testuser +12345
Password cannot start with '+', please try again.

.newpass 12345
Please use at least 6 characters.
.newpass 123456
Changed password to '123456'.
.newpass 123456789012345
Changed password to '123456789012345'.
.newpass 1234567890123456
Passwords cannot be longer than 15 characters, please try again.
.newpass +12345
Password cannot start with '+', please try again.
```

**Comment by michaelortmann** [comment]
Developer test /msg
```
.chpass testuser testpass
Changed password.

-> *BotA* pass testpass 12345
-BotA- Please use at least 6 characters.
-> *BotA* pass testpass 123456
-BotA- Password changed to: '123456'.
-> *BotA* pass 123456 123456789012345
-BotA- Password changed to: '123456789012345'.
-> *BotA* pass 123456789012345 1234567890123456
-BotA- Passwords cannot be longer than 15 characters, please try again.
-> *BotA* pass 123456789012345 +12345
-BotA- Password cannot start with '+', please try again.
```

**Comment by michaelortmann** [comment]
Ready for review once again.

**Pull request merged**
