### PR TITLE
Fix Array bounds error

### LINKED ISSUE #840: Array bounds error
gcc 9.1.0, default cflags:

```
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c flags.c
flags.c: In function ‘break_down_flags’:
flags.c:387:10: warning: array subscript 1 is outside array bounds of ‘char[1]’ [-Warray-bounds]
  387 |   while (*string) {
      |          ^~~~~~~
```

I looked into it very hard, and as always, the compiler was right.

See:

https://github.com/eggheads/eggdrop/blob/develop/src/flags.c#L406
https://github.com/eggheads/eggdrop/blob/develop/src/flags.c#L448
https://github.com/eggheads/eggdrop/blob/develop/src/flags.c#L387

Pseudocode:

```
while (*string) { /* Array bounds error if the following "if" is triggered */
  if [...]
    string = "";
  string++;
}
```

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: michaelortmann
Patch by: michaelortmann
Fixes: #840 

One-line summary:
Fix Array bounds error and compiler warning.

Additional description (if needed):
Security issue with low severity level.

Test cases demonstrating functionality (if applicable):
My first commit to this PR was a patch to demo the bug:
```
.chattr testuser ||
[02:10:12] tcl: builtin dcc call: *dcc:chattr -HQ 1 testuser ||
[02:10:12] TEST840: string = ||
[02:10:12] TEST840: string = |
[02:10:12] TEST840: BOOM SHAKE SHAKE SHAKE THE ROOM
[02:10:12] TEST840: string = Usage: su <user>

[02:10:12] TEST840: string = sage: su <user>

[02:10:12] TEST840: string = age: su <user>

[02:10:12] TEST840: string = ge: su <user>

[02:10:12] TEST840: string = e: su <user>

[02:10:12] TEST840: string = : su <user>

[02:10:12] TEST840: string =  su <user>

[02:10:12] TEST840: string = su <user>

[02:10:12] TEST840: string = u <user>

[02:10:12] TEST840: string =  <user>

[02:10:12] TEST840: string = <user>

[02:10:12] TEST840: string = user>

[02:10:12] TEST840: string = ser>

[02:10:12] TEST840: string = er>

[02:10:12] TEST840: string = r>

[02:10:12] TEST840: string = >

[02:10:12] TEST840: string = 

[02:10:12] #-HQ# chattr testuser ||
```
With this patch the bug and the following compiler warning (gcc 9.1.0, default cflags) is fixed:
```
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/include -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c flags.c
flags.c: In function ‘break_down_flags’:
flags.c:387:10: warning: array subscript 1 is outside array bounds of ‘char[1]’ [-Warray-bounds]
  387 |   while (*string) {
      |          ^~~~~~~
```

### CODE REVIEW

**Comment by michaelortmann** [comment]
Alternative solutions would include goto, continue, replacing the global string++ with many local string++s excluding the _one_ case, refactoring into function with return instead of break and refactoring the whole function. The goto solution has some charm, its explicit and it avoids 1 useless setting and checking for string. Do you prefer the goto or the string = "\0" solution? **If you prefer goto, i would like to change the patch accordingly. If not, this patch is ready for review and merge.**

**Comment by thommey** [comment]
goto sounds better, agreed

**Comment by michaelortmann** [comment]
> goto sounds better, agreed

Done. Ready for review again.

**Review by thommey — APPROVED** [review]
LGTM

**Pull request merged**
