### PR TITLE
Fix usage of SSL_CIPHER_description() under OpenSSL ver < 0.9.8m-beta1

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Fix usage of SSL_CIPHER_description() under OpenSSL ver < 0.9.8m-beta1

Additional description (if needed):
OpenSSL changed API for SSL_CIPHER_description()
Fix a compiler warning for OpenSSL version < 0.9.8m-beta1

Test cases demonstrating functionality (if applicable):
64-bit OpenBSD 4.7 gcc 3.3.5 Tcl 8.5.8 **OpenSSL 0.9.8k** CFLAGS default

```
$ make
[...]
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/local/include/tcl8.5 -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c tls.c
tls.c: In function `ssl_info':
tls.c:667: warning: passing arg 1 of `SSL_CIPHER_description' discards qualifiers from pointer target type
```

### CODE REVIEW

**Comment by Cizzle** [comment]
Are you sure? When checking the doc of openssl-0.9.8zh it claims to use `const SSL_CIPHER *cipher` as first arg. So maybe not <= 1.0.0 but <= 0.9.?

**Comment by michaelortmann** [comment]
thank you for finding the flaw and binsecting thru openssl releases :)

**Comment by Cizzle** [comment]
LGTM

**Comment by vanosg** [comment]
build

**Pull request merged**
