### PR TITLE
Fail early on TLS certificate loading errors.

### LINKED ISSUE #447: OpenSSL: temporary CTX with testing cert/key or invalidate cert after
right now, we load the certificate into the global ssl_ctx, and then load the key.
1) we don't verify the key with SSL_CTX_check_private_key
2) we can't "unset" the certificate if they key is invalid or doesn't exist, so we should use a temporary ssl_ctx to do that

### PR DESCRIPTION
**Pull request by thommey**
Fatal on cert loading errors and report unsupported STARTTLS to LOG_MISC.

PR based on #445 bug/sslmsg

Fixes #447

### CODE REVIEW

**Comment by Cizzle** [comment]
LGTM

**Comment by vanosg** [comment]
Tests added. 

Do we want to kill eggdrop if privatekey is set, but certificate is commented out? Currently we just warn, but we kill if one of those settings points at a non-existent file... this would feel a little more like a standard behavior to me. If yes, I (or you) can add; otherwise, LGTM :+1:

**Comment by vanosg** [comment]
Per thommey, kill the bastard.

**Comment by Cizzle** [comment]
Still LGTM.

**Pull request merged**
