### PR TITLE
Update Config files to latest version

### PR DESCRIPTION
**Pull request by odidev**
Config.guess and config.sub files are updated to enhance support
for other architectures as well.
This enhances eggdrop support for ARM64v8 too.

Signed-off-by: Akhil Gupta <akhil.gupta@puresoftware.com>

Fixes: configuration support issue for arm64v8.

One-line summary:

Additional description (if needed):

Test cases demonstrating functionality (if applicable):

### CODE REVIEW

**Review by lag-linaro — APPROVED** [review]
Updating 10 year old config files to something more recent is a good idea.

Acked-by: Lee Jones <lee.jones@linaro.org>

**Comment by Cizzle** [comment]
LGTM

**Comment by lag-linaro** [comment]
Thanks for merging this PR.

Since the addition of new architectures is such a big milestone, do you think it could help warrant a version bump?  It does look as though your Docker Hub project specifies 1.8.3 which is quite a number of months old now.

**Comment by odidev** [comment]
@vanosg : Can you please point out whether these changes will be merged in ongoing ```eggdrop-1.8.3``` version or is there any new version being planned for eggdrop release.
I think that needs to be updated in the ```dockerfile``` too to add support for ```arm64v8``` in official eggdrop docker.

**Pull request closed without merging**
