### PR TITLE
Cleanup tell_user functions

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Cleanup tell_user functions

Additional description (if needed):
1. Delete unused parameters of tell_user()
(master flag was not used and is not necessary because userent.c:comment_display() already checks for master flag to display COMMENT)
2. Make tell_user() static
3. Cleanup tell_user_ident() and tell_users_match()

Test cases demonstrating functionality (if applicable):

### CODE REVIEW

**Comment by Cizzle** [comment]
You can safely remove those unused params, proto.h has nothing to do with the modules.

**Comment by michaelortmann** [comment]
@Cizzle: Ty, its done.

**Comment by Cizzle** [comment]
LGTM

**Comment by vanosg** [comment]
build

**Pull request merged**
