### PR TITLE
Try to avoid race for ident

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: PeGaSuS
Patch by: michaelortmann
Fixes: 

One-line summary:
Try to avoid race for ident

Additional description (if needed):
Pls give this patch a try. Its makeing eggdrops code a little bit more complex, but right now, this is all i can do.

The idea implemented here is, like:

In server mod `server_resolve_success()` we called `open_telnet_raw()` and then `check_tcl_event("ident")`.

`open_telnet_raw()` calls `connect()`.

In my test, there is code executed between `connect()` and return from  called `open_telnet_raw()`.

That code is executed because we async connect. I spare the details.

The important part is, that there is code executed between `connect()` and `check_tcl_event("ident")` widening the race window.

This patch does move the `check_tcl_event("ident")` as close as possible to the `connect()` call. Even if we are not fully connected yet, we already have what we need.

Yes, it could be we do the ident-setup and then the connect() fails, but this is no problem, in this case we just wasted some cpu cycles and a needlessly write to the oident config file.

Review and merge only, if this PR fixes the problem for PeGaSuS..

Test cases demonstrating functionality (if applicable):

### CODE REVIEW

**Comment by michaelortmann** [comment]
meanwhile, i can repeat the problem.

Is it triggert when using ssl connect.

Before this PR:
```
.jump moon.freenode.net +6697

tcpdump  -i br0 port 113 -XXX

16:09:29.371853 IP zen.localdomain.ident > moon.freenode.net.39059: Flags [P.], seq 1:33, ack 15, win 509, options [nop,nop,TS val 1323787391 ecr 3259111282], length 32
	0x0000:  444e 6dd4 fa4e 7206 5956 b518 0800 4500  DNm..Nr.YV....E.
	0x0010:  0054 7391 4000 4006 d6ab c0a8 0103 ade6  .Ts.@.@.........
	0x0020:  80d5 0071 9893 1ac5 5491 dd02 cbfc 8018  ...q....T.......
	0x0030:  01fd f0ad 0000 0101 080a 4ee7 647f c242  ..........N.d..B
	0x0040:  1772 3432 3538 312c 3636 3937 3a55 5345  .r42581,6697:USE
	0x0050:  5249 443a 554e 4958 3a6d 6963 6861 656c  RID:UNIX:michael
	0x0060:  0d0a
```

After this PR:
```
.jump moon.freenode.net +6697

tcpdump  -i br0 port 113 -XXX

16:12:02.124839 IP zen.localdomain.ident > moon.freenode.net.50009: Flags [P.], seq 1:30, ack 15, win 509, options [nop,nop,TS val 1323940144 ecr 3259264034], length 29
	0x0000:  444e 6dd4 fa4e 7206 5956 b518 0800 4500  DNm..Nr.YV....E.
	0x0010:  0051 7774 4000 4006 d2cb c0a8 0103 ade6  .Qwt@.@.........
	0x0020:  80d5 0071 c359 26c3 532b 3bbe 542b 8018  ...q.Y&.S+;.T+..
	0x0030:  01fd f0aa 0000 0101 080a 4ee9 b930 c244  ..........N..0.D
	0x0040:  6c22 3334 3031 392c 3636 3937 3a55 5345  l"34019,6697:USE
	0x0050:  5249 443a 554e 4958 3a42 6f74 410d 0a    RID:UNIX:BotA..
```

**Comment by michaelortmann** [comment]
Additional debug log from a "failed" ident:

eggdrop log:
```
[17:12:19] net: open_telnet_raw(): idx 4 host moon.freenode.net ip 173.230.128.213 port 6697 ssl 1
[17:12:20] ######## open_telnet_raw() returned
[17:12:20] TLS: attempting SSL negotiation...
```

I inserted the putlog "`######## open_telnet_raw() returned`" right after line: https://github.com/eggheads/eggdrop/blob/5012919e7437903d2dc489b7b5824d664bc1d0f3/src/mod/server.mod/servmsg.c#L1941

```
tcpdump:

17:12:19.769354 IP moon.freenode.net.47365 > zen.localdomain.ident: Flags [P.], seq 1:15, ack 1, win 502, options [nop,nop,TS val 3262881692 ecr 1327557669], length 14
	0x0000:  7206 5956 b518 444e 6dd4 fa4e 0800 4500  r.YV..DNm..N..E.
	0x0010:  0042 6d99 4000 3506 e7b5 ade6 80d5 c0a8  .Bm.@.5.........
	0x0020:  0103 b905 0071 7e09 1f25 e1d3 3e98 8018  .....q~..%..>...
	0x0030:  01f6 27b6 0000 0101 080a c27b 9f9c 4f20  ..'........{..O.
	0x0040:  ec25 3437 3635 3520 2c20 3636 3937 0d0a  .%47655.,.6697..
```

This means, the irc server sends the ident request and it was captured by tcpdump on eggdrops machine before the connecttion to the irc server is fully done. connect() returned, but it is async connect(). So, while the ident packet arrives, eggdrop is in the following code block and has not returned from open_telnet_raw() yet:
https://github.com/eggheads/eggdrop/blob/5012919e7437903d2dc489b7b5824d664bc1d0f3/src/net.c#L566

**Comment by michaelortmann** [comment]
About that speedup patch:

its a byproduct of this PR and it will speed up connects() for some cases.

There is a select() with an arbitrary timeout value:

https://github.com/eggheads/eggdrop/blob/5012919e7437903d2dc489b7b5824d664bc1d0f3/src/net.c#L573

In the case analyzed in this PR (connecting to an ssl port of an ircd-seven like freenode), that timeout is hit, slowing eggdrops connection process needlessly down by 1 full sec.

I dont have the courage to make the timeout near zero, but to change it from 1 sec to 1/10 cant hurt, but will speed up eggdrops connect() for some cases by factor of 10!

Here is a log for an ssl connect to an irc server. if you try this without this PR applied, you will get alog, typically showing one more sec spend while connecting:

```
.jump 127.0.0.1 +6697
[20:27:05] tcl: builtin dcc call: *dcc:jump -HQ 1 127.0.0.1 +6697
[20:27:05] #-HQ# jump 127.0.0.1 +6697 
Jumping servers......
[20:27:06] Trying server 127.0.0.1:+6697
[20:27:06] net: open_telnet_raw(): idx 4 host 127.0.0.1 ip 127.0.0.1 port 6697 ssl 1
[20:27:06] TLS: attempting SSL negotiation...
[20:27:06] TLS: setting the server name indication (SNI) to 127.0.0.1 successful
[20:27:06] TLS: state change: before SSL initialization
[20:27:06] TLS: state change: before SSL initialization
[20:27:06] TLS: state change: SSLv3/TLS write client hello
[20:27:06] TLS: awaiting more reads
[20:27:06] TLS: handshake in progress
[20:27:06] TLS: awaiting more reads
[20:27:06] TLS: awaiting more reads
[20:27:06] dequeue_sockets(): errno = 11 (Resource temporarily unavailable) on 10
[20:27:06] TLS: state change: SSLv3/TLS write client hello
[20:27:06] TLS: state change: SSLv3/TLS read server hello
[20:27:06] TLS: state change: TLSv1.3 read encrypted extensions
[20:27:06] TLS: state change: SSLv3/TLS read server certificate request
[20:27:06] TLS: peer certificate warning: self signed certificate
[20:27:06] TLS: peer certificate warning: certificate has expired
[20:27:06] TLS: state change: SSLv3/TLS read server certificate
[20:27:06] TLS: state change: TLSv1.3 read server certificate verify
[20:27:06] TLS: state change: SSLv3/TLS read finished
[20:27:06] TLS: state change: SSLv3/TLS write change cipher spec
[20:27:06] TLS: state change: SSLv3/TLS write client certificate
[20:27:06] TLS: state change: SSLv3/TLS write certificate verify
[20:27:06] TLS: state change: SSLv3/TLS write finished
[20:27:06] TLS: handshake successful. Secure connection established.
[20:27:06] TLS: certificate subject: C=DE, ST=Some-State, O=Internet Widgits Pty Ltd
[20:27:06] TLS: certificate issuer: C=DE, ST=Some-State, O=Internet Widgits Pty Ltd
[20:27:06] TLS: certificate SHA1 Fingerprint: 8E:74:50:E9:1D:B7:ED:D0:71:C8:5B:3B:F6:29:D5:E6:83:1B:95:74
[20:27:06] TLS: certificate SHA-256 Fingerprint: E6:19:3B:7F:84:EC:E0:61:8A:A5:94:54:AB:B4:97:74:94:F2:5D:B5:08:2D:BB:D5:08:7C:34:43:C3:6B:72:27
[20:27:06] TLS: certificate valid from Oct  5 22:33:32 2018 GMT to Oct  5 22:33:32 2019 GMT
[20:27:06] TLS: cipher used: TLS_AES_256_GCM_SHA384 TLSv1.3; 256 bits (256 secret)
[20:27:06] TLS: cipher details: TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD

[20:27:06] sockread EAGAIN: 10 11 (Resource temporarily unavailable)
[20:27:06] net: connect! sock 10
[20:27:06] Connected to 127.0.0.1
[20:27:06] TLS: state change: SSL negotiation finished successfully
[20:27:06] TLS: state change: SSL negotiation finished successfully
[20:27:06] TLS: state change: SSLv3/TLS read server session ticket
[20:27:06] TLS: state change: SSL negotiation finished successfully
[20:27:06] TLS: state change: SSL negotiation finished successfully
[20:27:06] TLS: state change: SSLv3/TLS read server session ticket
[20:27:06] -NOTICE- *** Looking up your hostname...
[20:27:06] -NOTICE- *** Checking Ident
[20:27:06] -NOTICE- *** Found your hostname
[20:27:06] -NOTICE- *** Got Ident response
[20:27:06] CAP: LS :account-notify away-notify cap-notify chghost extended-join identify-msg multi-prefix sasl tls
[...]
```

hooray!

**Comment by michaelortmann** [comment]
Log of select timeout before this PR:

you can clearly see the 1 sec timeout in the select() in the 2 log lines:
```
[21:01:36] net: open_telnet_raw(): idx 4 host 127.0.0.1 ip 127.0.0.1 port 6697 ssl 1
[21:01:37] TLS: attempting SSL negotiation...
```

```
.jump 127.0.0.1 +6697
[21:01:36] tcl: builtin dcc call: *dcc:jump -HQ 1 127.0.0.1 +6697
[21:01:36] #-HQ# jump 127.0.0.1 +6697 
Jumping servers......
[21:01:36] Trying server 127.0.0.1:+6697
[21:01:36] net: open_telnet_raw(): idx 4 host 127.0.0.1 ip 127.0.0.1 port 6697 ssl 1
[21:01:37] TLS: attempting SSL negotiation...
[21:01:37] TLS: setting the server name indication (SNI) to 127.0.0.1 successful
[21:01:37] TLS: state change: before SSL initialization
[21:01:37] TLS: state change: before SSL initialization
[21:01:37] TLS: state change: SSLv3/TLS write client hello
[21:01:37] TLS: awaiting more reads
[21:01:37] TLS: handshake in progress
[21:01:37] TLS: awaiting more reads
[21:01:37] TLS: state change: SSLv3/TLS write client hello
[21:01:37] TLS: state change: SSLv3/TLS read server hello
[21:01:37] TLS: state change: TLSv1.3 read encrypted extensions
[21:01:37] TLS: state change: SSLv3/TLS read server certificate request
[21:01:37] TLS: peer certificate warning: self signed certificate
[21:01:37] TLS: peer certificate warning: certificate has expired
[21:01:37] TLS: state change: SSLv3/TLS read server certificate
[21:01:37] TLS: state change: TLSv1.3 read server certificate verify
[21:01:37] TLS: state change: SSLv3/TLS read finished
[21:01:37] TLS: state change: SSLv3/TLS write change cipher spec
[21:01:37] TLS: state change: SSLv3/TLS write client certificate
[21:01:37] TLS: state change: SSLv3/TLS write certificate verify
[21:01:37] TLS: state change: SSLv3/TLS write finished
[21:01:37] TLS: handshake successful. Secure connection established.
[21:01:37] TLS: certificate subject: C=DE, ST=Some-State, O=Internet Widgits Pty Ltd
[21:01:37] TLS: certificate issuer: C=DE, ST=Some-State, O=Internet Widgits Pty Ltd
[21:01:37] TLS: certificate SHA1 Fingerprint: 8E:74:50:E9:1D:B7:ED:D0:71:C8:5B:3B:F6:29:D5:E6:83:1B:95:74
[21:01:37] TLS: certificate SHA-256 Fingerprint: E6:19:3B:7F:84:EC:E0:61:8A:A5:94:54:AB:B4:97:74:94:F2:5D:B5:08:2D:BB:D5:08:7C:34:43:C3:6B:72:27
[21:01:37] TLS: certificate valid from Oct  5 22:33:32 2018 GMT to Oct  5 22:33:32 2019 GMT
[21:01:37] TLS: cipher used: TLS_AES_256_GCM_SHA384 TLSv1.3; 256 bits (256 secret)
[21:01:37] TLS: cipher details: TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD

[21:01:37] sockread EAGAIN: 10 11 (Resource temporarily unavailable)
[21:01:37] net: connect! sock 10
[21:01:37] Connected to 127.0.0.1
[21:01:37] TLS: state change: SSL negotiation finished successfully
[21:01:37] TLS: state change: SSL negotiation finished successfully
[21:01:37] TLS: state change: SSLv3/TLS read server session ticket
[21:01:37] TLS: state change: SSL negotiation finished successfully
[21:01:37] TLS: state change: SSL negotiation finished successfully
[21:01:37] TLS: state change: SSLv3/TLS read server session ticket
[21:01:37] -NOTICE- *** Looking up your hostname...
[21:01:37] -NOTICE- *** Checking Ident
[21:01:37] -NOTICE- *** Found your hostname
[21:01:37] -NOTICE- *** Got Ident response
[21:01:37] CAP: LS :account-notify away-notify cap-notify chghost extended-join identify-msg multi-prefix sasl tls
```

**Comment by Cizzle** [comment]
LGTM

**Pull request merged**
