### PR TITLE
Fix channels output for .who linkedbot

### PR DESCRIPTION
**Pull request by Cizzle**
Found by: Cizzle
Patch by: Cizzle
Fixes: part of #69 recheck

One-line summary: fixes the Channels output when issuing ".who linkedbot" on partyline.

Additional description (if needed): Also fixes the first error of issue #69 recheck and added truncation symbols "..." when channelslist is longer than the max defined in eggdrop (450 - strlen(eggdrop version) - 3)

Test cases demonstrating functionality (if applicable): .who linkedbot
This will not show the "Channels: " text before the channels and for long channellists (over 450 chars) the last channel being cutoff and no eggdrop version showing anymore.

### CODE REVIEW

**Comment by vanosg** [comment]
build

**Comment by vanosg** [comment]
build

**Comment by Cizzle** [comment]
Tested truncation of channames too long for one line by changing the size of "s" to 50 and doing the same at [L303 of src/botmsg.c](https://github.com/eggheads/eggdrop/blob/develop/src/botmsg.c#L303).

**Comment by vanosg** [comment]
build

**Pull request merged**
