### PR TITLE
Release/1.9.0 Italian language file

### PR DESCRIPTION
**Pull request by carlin0**
One-line summary:
Italian language file : the files are here → https://gitlab.com/carlin0/eggdrop/-/tree/master/lang

### CODE REVIEW

**Comment by vanosg** [comment]
@carlin0 thanks so much for taking the time and effort to submit this! Is it possible for you to make the changes on the develop branch, instead of the release/1.9.0 branch? If you hang out in the channel, I can walk you through it if you're not familiar with the process when we are both around. 

Again, thank you for this! Another language is a huge victory for Eggdrop

**Comment by vanosg** [comment]
Apologies, I'm just looking more at this PR- I see your files are hosted on GitLab (and I don't see them included as part of this pull request). Since you have a GH account now, you can either make the changes in a directory cloned from GitHub and you can get credit in the git history; or if it is too much hassle I can merge them in on your behalf and credit you, you just don't get to see your account linked directly as a contributor. Either way is fine, and I'm happy to help walk you through any questions you have in #eggdrop. Don't get discouraged if this is confusing :)

**Comment by carlin0** [comment]
@vanosg I'm sorry I'm newbie on this thing, and I wouldn't know how to do what you ask me, you should be kind enough to put my gitlab files here and to make the necessary changes to what I was wrong here

**Comment by vanosg** [comment]
No worries! I will fix this up tonight in a new PR and give you credit in the notes, if that works for you. Thanks again

**Comment by carlin0** [comment]
it's okay for me, and thanks for your patience

**Comment by vanosg** [comment]
Added! Thanks again for taking the time to contribute this, I know it is a lot of work.

**Pull request closed without merging**
