### PR TITLE
Fix default settings by net-type and add net-types

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Fix default settings by net-type, add net-types (freenode, QuakeNet, Rizon) and changed net-type from int to string

Additional description (if needed):
Last station before proper numeric 005 support.
Some networks updated NICKLEN and other settings.
005 support could be backward compatible, with net-type as fallback, so ppl could leave net-type in their eggdrop.conf without problems.
Most of the net-type settings are from current server messages:
**freenode:**
```
*** Connecting to port 6667 of server irc.freenode.org
*** Welcome to the freenode Internet Relay Chat Network [...] (from card.freenode.net)
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is card.freenode.net[38.229.70.22/6667], running version ircd-seven-1.1.7
*** This server was created Tue Sep 25 2018 at 13: 22:00 UTC
*** umodes available DOQRSZaghilopswz, channel modes available CFILMPQSbcefgijklmnopqrstvz
*** CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#: 120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 are supported by this server
*** CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES: 1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 KNOCK CPRIVMSG CNOTICE are supported by this server
*** WHOX SAFELIST ELIST=CTU ETRACE are supported by this server
*** There are 94 users and 84883 invisible on 27 servers
*** 84977 94773 Current global users 84977, max 94773
```
**IRCnet:**
```
*** Connecting to port 6667 of server irc.fu-berlin.de
*** Welcome to the Internet Relay Network [...] (from fu-berlin.de)
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is fu-berlin.de, running version 2.11.2p3
*** This server was created Wed Jun 28 2017 at 14: 02:12 CEST
*** umodes available aoOirw, channel modes available abeiIklmnoOpqrRstv
*** RFC2812 PREFIX=(ov)@+ CHANTYPES=#&!+ MODES=3 CHANLIMIT=#&!+: 21 NICKLEN=15 TOPICLEN=255 KICKLEN=255 MAXLIST=beIR:64 CHANNELLEN=50 IDCHAN=!:5 CHANMODES=beIR,k,l,imnpstaqr are supported by this server
*** PENALTY FNC EXCEPTS=e INVEX=I CASEMAPPING=ascii NETWORK=IRCnet are supported by this server
*** 276BACPW7 your unique ID
*** There are 26469 users and 1 services on 27 servers
*** 26469 28916 Current global users 26469, max 28916
```
**EFnet:**
```
** Connecting to port 6667 of server irc.inet.tele.dk
*** Welcome to the EFNet Internet Relay Chat Network [...] (from efnet.deic.eu)
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is efnet.deic.eu[130.226.213.194/6667], running version ircd-ratbox-3.0.10
*** This server was created Sat Mar 9 2019 at 18: 45:12 CET
*** umodes available oiwszcrkfydnxbauglZCD, channel modes available biklmnopstveIrS
*** CHANTYPES=&# EXCEPTS INVEX CHANMODES=eIb,k,l,imnpstS CHANLIMIT=&#: 20 PREFIX=(ov)@+ MAXLIST=beI:100 MODES=4 NETWORK=EFNet KNOCK STATUSMSG=@+ CALLERID=g are supported by this server
*** SAFELIST ELIST=U CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=9 CHANNELLEN=50 TOPICLEN=160 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=60 are supported by this server
*** FNC ACCEPT=20 MAP TARGMAX=NAMES: 1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: are supported by this server
*** There are 5248 users and 10139 invisible on 22 servers
*** 15387 19386 Current global users 15387, max 19386
```
**Undernet:**
```
*** Connecting to port 6667 of server Budapest.HU.EU.UnderNet.org
*** Welcome to the UnderNet IRC Network, [...]
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is Budapest.Hu.Eu.Undernet.org, running version u2.10.12.19
*** This server was created Mon Apr 1 2019 at 01: 31:30 CEST
*** umodes available diOoswkgx, channel modes available biklmnopstvrDdRcC
*** WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE SILENCE=25 MODES=6 MAXCHANNELS=30 MAXBANS=100 NICKLEN=12 are supported by this server
*** MAXNICKLEN=15 TOPICLEN=160 AWAYLEN=160 KICKLEN=160 CHANNELLEN=200 MAXCHANNELLEN=200 CHANTYPES=#& PREFIX=(ov)@+ STATUSMSG=@+ CHANMODES=b,k,l,imnpstrDdRcC CASEMAPPING=rfc1459 NETWORK=UnderNet are supported by this server
*** There are 3337 users and 10654 invisible on 35 servers
```
**QuakeNet:**
```
*** Connecting to port 6667 of server irc.quakenet.org
*** Welcome to the QuakeNet IRC Network, [...] (from underworld2.no.quakenet.org)
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is underworld2.no.quakenet.org, running version u2.10.12.10+snircd(1.3.4a)
*** This server was created Fri May 24 2013 at 22: 12:24 CEST
*** umodes available dioswkgxRXInP, channel modes available biklmnopstvrDcCNuMT
*** WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE SILENCE=15 MODES=6 MAXCHANNELS=20 MAXBANS=45 NICKLEN=15 are supported by this server
*** MAXNICKLEN=15 TOPICLEN=250 AWAYLEN=160 KICKLEN=250 CHANNELLEN=200 MAXCHANNELLEN=200 CHANTYPES=#& PREFIX=(ov)@+ STATUSMSG=@+ CHANMODES=b,k,l,imnpstrDducCNMT CASEMAPPING=rfc1459 NETWORK=QuakeNet are supported by this server
*** There are 16 users and 12232 invisible on 28 servers
```
**Rizon:**
```
*** Connecting to port 6667 of server irc.rizon.net
*** Welcome to the Rizon Internet Relay Chat Network [...] (from irc.x2x.cc)
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is irc.x2x.cc, running version plexus-4(hybrid-8.1.20)
*** This server was created Dec  5 2018 at 16: 16:55
*** umodes available CDGNRSUWagilopqrswxyz, channel modes available BCIMNORSabcehiklmnopqstvz
*** CALLERID CASEMAPPING=rfc1459 DEAF=D KICKLEN=180 MODES=4 PREFIX=(qaohv)~&@%+ STATUSMSG=~&@%+ EXCEPTS=e INVEX=I NICKLEN=30 NETWORK=Rizon MAXLIST=beI: 250 MAXTARGETS=4 :are supported by this server
*** CHANTYPES=# CHANLIMIT=#: 250 CHANNELLEN=50 TOPICLEN=390 CHANMODES=beI,k,l,BCMNORScimnpstz NAMESX UHNAMES ELIST=CMNTU SAFELIST AWAYLEN=180 WATCH=60 KNOCK are supported by this server
*** There are 50 users and 11787 invisible on 17 servers
*** Current global users:  11837  Max: 19437
```
**DALnet:**
```
*** Connecting to port 6667 of server underworld.se.eu.dal.net
*** Welcome to the DALnet IRC Network [...]
*** If you have not already done so, please read the new user information with /HELP NEWUSER
*** Your host is underworld.se.eu.dal.net, running version bahamut-2.1.4
*** This server was created Thu Dec 20 2018 at 20: 23:54 CET
*** umodes available aAbcCdefFghHiIjkKmnoOPrRsSwxXy, channel modes available AbceiIjklLmMnoOpPrRsStv
*** NETWORK=DALnet SAFELIST MAXBANS=200 MAXCHANNELS=40 CHANNELLEN=32 KICKLEN=307 NICKLEN=30 TOPICLEN=307 MODES=6 CHANTYPES=# CHANLIMIT=#: 40 PREFIX=(ov)@+ STATUSMSG=@+ :are available on this server
*** CASEMAPPING=ascii WATCH=128 SILENCE=10 ELIST=cmntu EXCEPTS INVEX CHANMODES=beI,k,jl,cimMnOprRsSt MAXLIST=b: 200,e:100,I:100 TARGMAX=DCCALLOW:,JOIN:,KICK:4,KILL:20,NOTICE:20,PART:,PRIVMSG:20,WHOIS:,WHOWAS: are available on this server
*** There are 29 users and 7452 invisible on 45 servers
*** Current global users:  7481 Max: 9949
```

Test cases demonstrating functionality (if applicable):
**Test 1:**
```
$ grep -R "set net-type" BotA.conf
set net-type "freenode"
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.9.0+sasl (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
[...]
.set net-type
[07:04:09] tcl: builtin dcc call: *dcc:set -HQ 1 net-type
[07:04:09] #-HQ# set net-type
Currently: freenode
.set nick-len
[07:04:25] tcl: builtin dcc call: *dcc:set -HQ 1 nick-len
[07:04:25] #-HQ# set nick-len
Currently: 16
```
**Test 2:**
```
$ grep -R "set net-type" BotA.conf
set net-type 1
$ ./eggdrop -nt BotA.conf 

Eggdrop v1.9.0+sasl (C) 1997 Robey Pointer (C) 2010-2018 Eggheads
[...]
.set net-type
[08:09:45] tcl: builtin dcc call: *dcc:set -HQ 1 net-type
[08:09:45] #-HQ# set net-type
Currently: IRCnet
.set nick-len
[08:09:56] tcl: builtin dcc call: *dcc:set -HQ 1 nick-len
[08:09:56] #-HQ# set nick-len
Currently: 15
```

### CODE REVIEW

**Review by thommey — APPROVED** [review]

**Comment by thommey** [comment]
great usability improvement for now!

**Comment by vanosg** [comment]
build

**Comment by vanosg** [comment]
So, here's my OCD kicking in. From a human factors perspective,  "Other" is generally the last choice in a list. However, old configs have 5 as other. 

Could we:
a) Wait until 1.9 to move these options around
b) make the list 1,2,3,4,6,7,8,9) Other , with 5) being a 'hidden' choice?

I think b) just digs a bigger hole for the future. I know this is a simple but good tweak, but... for OCD's sake, could we hold off until 1.9 and slide 'Other' down the list to where it belongs?

**Comment by thommey** [comment]
that would be needlessly breaking older configs and making migration to 1.9 harder. simply moving the documentation for "5) other" to the bottom should do the trick, no?

**Comment by vanosg** [comment]
What about removing 5 from the config (but leaving it in the code and warning on startup), and adding it back as 9? In short, both 5 and 9 both map to 'Other'

... or making it '99'?

**Comment by michaelortmann** [comment]
Why not leave 5 = Other, and add documentation into the config file, that explains, why Other isn't the 1st or last Choice but 5 for backward compatibility.

**Review by thommey — APPROVED** [review]
In general, I think it would be beneficial to move from numbers to strings, e.g.
set net-type "DALnet", set net-type "QuakeNet", and document them like that -- keeping the numbers around for compatibility internally

**Comment by michaelortmann** [comment]
@thommey: great solution, ill implement it now.

**Comment by michaelortmann** [comment]
@thommey: your great idea is implemented now, **ready for review again.**

**Comment by michaelortmann** [comment]
@thommey: your great idea is implemented now. I also checked which irc servers / settings the added networks use, and rebased the added net-types and settings. I'm not sure about hybrid-7+ because the net-type Hybrid was done for hybrid-6 and currently the networks use hybrid-7 and hybrid-8, some with patches. **Can someone tell me, if net-type EFnet or net-type Hybrid is better suited to hybrid-7/hybrid-8/ircd-ratbox and why?** Seems like kick_method is defined in irc and server mod, we may want to define it only in server.mod and export it via module api to irc.mod? We need to update `help` and `doc`. After this PR is done, the twitch Issue/PR will add the net-type twitch.

**Review by vanosg — APPROVED** [review]
LGTM! That was a surprising amount of work

**Pull request merged**
