### PR TITLE
Fix links to binds

### PR DESCRIPTION
**Pull request by slyngshede**
Link to list of all bind commands seem to be wrong.

### CODE REVIEW

**Comment by vanosg** [comment]
Great catch, thank you for taking the time to submit a PR on this! Feel free to add more hyperlinks throughout the documentation elsewhere :)

**Comment by vanosg** [comment]
Looks like there's one more old URL at the top of the doc, do you want to change that one too? I can hit it later if not.

**Comment by slyngshede** [comment]
It looks like I butchered the commit. Do you need me to do a new PR with just one commit?

**Comment by vanosg** [comment]
Nope, you did it perfectly, everything looks great. Thanks!

**Pull request merged**
