### PR TITLE
(Fix #560) Synchronize documentation/function for passwdok command

### LINKED ISSUE #560: PASSWDOK doesn't obey docs
The docs say: you can test if a user has a blank password (or had their password blanked) if you test against "" (empty string), or "-" 

... which is a lie.

\<Domino> ## adduser DELETEME
\<Samantha> [TCL (0ms)] 1
\<Domino> ## passwdok DELETEME  ""
\<Samantha> [TCL (0ms)] 0
\<Domino> 04## passwdok DELETEME -
\<Samantha> [TCL (0ms)] 1
--> Inconsistent

Before you ask: "does it do anything different if you set-then-clear the user's password?" ... it does not.

\<Domino> ##  setuser DELETEME PASS [encrypt [rand 999999999] [rand 999999999]]
\<&Samantha> [TCL (0ms)] 
\<Domino> ##  passwdok DELETEME  ""
\<&Samantha> [TCL (0ms)] 0
\<Domino> ##  passwdok DELETEME  -
\<&Samantha> [TCL (0ms)] 0
--> Correct responses.

\<Domino> ##  setuser DELETEME PASS
\<&Samantha> [TCL (0ms)] 
\<Domino> ##  passwdok DELETEME  ""
\<&Samantha> [TCL (0ms)] 0
\<Domino> ##  passwdok DELETEME  -
\<&Samantha> [TCL (0ms)] 1
--> Inconsistent again

Either the 1.8.1+RC1 encryption debacle broke this (...), the command has always been broken, or the docs have always been wrong.

Either way ....

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: maimizuno
Patch by: michaelortmann
Fixes: #560 

One-line summary:
fix doc, enhance doc and enhance code (readability and paranoid nullpointer check)

Additional description (if needed):

Test cases demonstrating functionality (if applicable):
.+user user1
[12:04:08] #-HQ# +user user1 
Added user1 (no host) with no password and no flags.
.chpass user1 123456 
[12:04:15] #-HQ# chpass user1 [something]
Changed password.
.+user user2
[12:04:18] #-HQ# +user user2 
Added user2 (no host) with no password and no flags.
.tcl passwdok user1 123456
Tcl: 1
.tcl passwdok user1 1234567
Tcl: 0
.tcl passwdok user1 -
Tcl: 0
.tcl passwdok user2 123456
Tcl: 0
.tcl passwdok user2 -
Tcl: 1

### CODE REVIEW

**Comment by Cizzle** [comment]
You should alter doc/sphinx_source/mainDocs/tcl-commands.rst as this is the source file from which the tcl-commands.doc is generated. Also please capitalise words who start a sentence, but I leave it to @vanosg to comment on the proper wording.

**Comment by Cizzle** [comment]
LGTM

**Comment by michaelortmann** [comment]
this patch touches a "security" function. i would like to see an additional LGTM from a second egghead before merge. thommey?

**Review by thommey — APPROVED** [review]
LGTM

**Pull request merged**
