### PR TITLE
Fix 'comparison is always false' / 'SIZEOF_SHORT undeclared' in dcc.c

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: michaelortmann
Patch by: michaelortmann
Fixes:

One-line summary:
Fix 'comparison is always false' / 'SIZEOF_SHORT undeclared' in dcc.c

Additional description (if needed):
found with OpenBSD 6.3 / gcc 4.2.1 20070719
maybe you can also see the compiler warning under different operating systems with CFLAGS += -Wtype-limits

Test cases demonstrating functionality (if applicable):

under openbsd 6.3 / gcc 4.2.1 20070719:
$ make

before:

```
[...]
gcc -g -O2 -pipe -Wall -I.. -I..  -DHAVE_CONFIG_H -I/usr/local/include/tcl8.6 -g3 -DDEBUG -DDEBUG_ASSERT -DDEBUG_MEM -DDEBUG_DNS  -c dcc.c
dcc.c: In function 'dcc_telnet':
dcc.c:1279: warning: comparison is always false due to limited range of data type
[...]
```

after: clean

### CODE REVIEW

**Review by thommey — CHANGES_REQUESTED** [review]
Change module export prototype for answer() in src/mod/module.h as well please

**Comment by michaelortmann** [comment]
@thommey: requested change done.

ready for review again.

**Comment by Cizzle** [comment]
LGTM

**Comment by vanosg** [comment]
build

**Pull request merged**
