### PR TITLE
Turn off Nagle's algorithm, see man tcp

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: simple
Patch by: michaelortmann
Fixes: 

One-line summary:
Turn off Nagle's algorithm, see man tcp 

Additional description (if needed):

Test cases demonstrating functionality (if applicable):

### CODE REVIEW

**Review by thommey — COMMENTED** [review]
I would only like this in conjunction with the \r\n change so we don't send an unnecessary amount of small packets

**Comment by michaelortmann** [comment]
The \r\n change has already been merged to develop with commit 2edf7064462beec3515cc8184f0ed7d09578769a.

**Comment by Cizzle** [comment]
LGTM

**Comment by vanosg** [comment]
build

**Pull request merged**
