### PR TITLE
(WIP) Add bind nickonce

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: Robby
Patch by: michaelortmann
Fixes: 

One-line summary:
Add bind nickonce

Additional description (if needed):
Nick binding doesnt trigger per user but per chan. An additional nickonce binding may be useful. Lets discuss it. And whats better to discuss than some actual code ;)

Test cases demonstrating functionality (if applicable):
Not tested yet.

### CODE REVIEW

**Comment by thommey** [comment]
I see the valid use-case, but I think there are other solutions for it. Such as triggering the bind with "*" as channel name once before triggering the channel binds. "nickonce" is too long for a bind name, they were limited to 4 chars last I checked.

Or maybe a "return 1" to stop triggering more of it (for the other channels)

**Comment by vanosg** [comment]
Correct on 4-char bind limits. This came from a question asked in channel about a NICK bind triggering multiple times if a user is in multiple chans with the bot. If * as the channel bind works (@Robby- have you tried this?) then I think this is not needed, but I would want to confirm * works the right way.

**Comment by vanosg** [comment]
```bind nick -|- * procname  ``` is the bind line in use (haven't tested first hand, but thats what Robby said). So this would imply * as a channel doesn't stop it. return 1 as part of the nick bind might be a pretty decent fix

**Comment by vanosg** [comment]
Addressed by 86de9fc ; in short use the RAWT bind with NICK as a  keyword to only trigger once per nick change, regardless of the number of channels the eggdrop and user share.

**Pull request closed without merging**
