### PR TITLE
Add summary with tcl, tls and ipv6 info to configure output.

### PR DESCRIPTION
**Pull request by Cizzle**
Found by: thommey
Patch by: Cizzle
Fixes: #264 

One-line summary: Adds a summary with Tcl, TLS and IPv6 results to the configure output next to the OS info.

Additional description (if needed): Also improved Tcl info gathering and small update of the configure script through autoconf which adds the --runstatedir option.

### CODE REVIEW

**Comment by vanosg** [comment]
build

**Comment by thommey** [comment]
I'd prefer yes/no output for IPv6/SSL so it's also clear that something was missing for it, as in:
SSL/TLS Support: no
IPv6: no
or something similar.

**Comment by vanosg** [comment]
Output appearance, at end of ./configure:
```
Operating System: Linux 4.4.0-59-generic
IPv6 Support: yes
Tcl version: 8.6.5 (threaded)
SSL/TLS Support: yes (OpenSSL 1.0.2g  1 Mar 2016)
```
and w/o TLS or IPv6:
```
Operating System: Linux 4.4.0-59-generic
IPv6 Support: no
Tcl version: 8.6.5 (threaded)
SSL/TLS Support: no
```


Great job, @Cizzle

**Comment by vanosg** [comment]
And just for historical purposes, a few more on different OSs:
```
Operating System: NetBSD 7.0
IPv6 Support: yes
Tcl version: 8.6.4 (threaded)
SSL/TLS Support: yes (OpenSSL 1.0.1p 9 Jul 2015)
```
```
Operating System: FreeBSD 11.0-RELEASE-p2
IPv6 Support: yes
Tcl version: 8.6.6 (threaded)
SSL/TLS Support: yes (OpenSSL 1.0.2j-freebsd  26 Sep 2016)
```
```
Operating System: OpenBSD 6.0
IPv6 Support: yes
Tcl version: 8.6.4 (threaded)
SSL/TLS Support: yes (LibreSSL 2.4.2)
```

**Pull request merged**
