### PR TITLE
Small french typos

### PR DESCRIPTION
**Pull request by crazycatdevs**
Found by: CrazyCat
Patch by: CrazyCat
Fixes: translation

One-line summary:
Small french typos

Additional description (if needed):

Test cases demonstrating functionality (if applicable):

### CODE REVIEW

**Comment by vanosg** [comment]
I'm curious why the diff's are showing changes to some lines without anything obvious appearing- are the accents maybe in a different encoding format now?

**Comment by vanosg** [comment]
build

**Comment by crazycatdevs** [comment]
> 
> 
> I'm curious why the diff's are showing changes to some lines without anything obvious appearing- are the accents maybe in a different encoding format now?

Seems to be encoding trouble, all lines with accentued characters show "changement"

**Comment by vanosg** [comment]
@crazycatdevs Thanks for this- I have a fix ready for encoding; can you enable the 'allow maintainers to push commits" or whatever that option is called, on this PR? I can push to here and then merge once you do. Thanks!

**Comment by crazycatdevs** [comment]
The "allow edits from maintainers" is checked, that's the only option I have.
Or must I close the PR ?

**Review by vanosg — APPROVED** [review]

**Pull request merged**
