### PR TITLE
Add account tracking to Eggdrop

### PR DESCRIPTION
**Pull request by vanosg**
This PR will add account support to Eggdrop. It must first be emphasized that the *proper* way to support this is to ensure that extended-join and account-notify capabilities are negotiated with the IRC server, as well as ensuring the server supports WHOX requests. This will ensure that Eggdrop is always kept notified of the current state of a user's account by the IRC server.

However, not all servers have these capabilities enabled. While not an ideal method to track account status and cannot be trusted to keep the userlist properly updated, the user can enable the account-tags capability (again, if the server supports it), and Eggdrop will update the account status of users in a channel based on the account tag provided when they speak. (**Question: Is this an always-when-account-tag-is-enabled capability, or is this a config option**)

In the ideal-case, to trigger a Tcl script that deals with accounts you'll need two paired binds- a JOIN bind to capture if the user is authenticated when they join a channel (information obtained via the extended-join capability) and an ACCOUNT bind to capture if the user authenticates inside the channel.

Eggdrop will now store account names in the userfile; similar to handles, account names must be unique across all users in Eggdrop (in other words, User1 and User2 cannot both have "Fooberry" assigned to them as an account name).

### Features
This PR adds
- .account command, to add (or remove) an account from a handle
- Tcl command account2hand, to get the handle associated with a provided account name
- Additional ways to update the account associated with a user

### Technical checks:

Account is updated when...

*Ideal cases*
- [x] a user joins (gotjoin)
- [x] bot joins (got352or4)
- [x] user authenticates (gotaccount)

*Best-effort cases*
- [x] user speaks (gotmsg)
- [x] user speaks in a different channel (gotmsg)
- [x] user joins and is already authenticated in a different channel (gotjoin)
- [x] bot joins a new channel shared with an existing user (got352or4)

To-Dos:
- Update account2hand code comments
- Check accounts for uniqueness prior to adding to a handle
- Fix bind documentation
- Add .account documentation

### CODE REVIEW

**Comment by crazycatdevs** [comment]
Seems to work (made a few tests, gonna have more tries with it).
Some warnings on make:
```
In file included from .././irc.mod/irc.c:70:
.././irc.mod/cmdsirc.c: In function ‘cmd_channel’:
.././irc.mod/cmdsirc.c:729:44: warning: variable ‘acctnotify’ set but not used [-Wunused-but-set-variable] int maxnicklen, maxhandlen, extjoin = 0, acctnotify = 0;                                    ^~~~~~~~~~
.././irc.mod/cmdsirc.c:729:31: warning: variable ‘extjoin’ set but not used [-Wunused-but-set-variable] int maxnicklen, maxhandlen, extjoin = 0, acctnotify = 0;
```

And when user join a channel, the bind account triggers 3 times:
```
14:44:19 --> CrazyCat [CrazyCat] (crazycat) (crazycat@zeolia.net) a rejoint #raspfr 
[14:44] triggering bind test:account
[14:44] CrazyCat is CrazyCat on #raspfr
[14:44] triggered bind test:account, user 0.544ms sys 0.229ms
[14:44] triggering bind test:account
[14:44] CrazyCat is CrazyCat on #raspfr
[14:44] triggered bind test:account, user 0.487ms sys 0.205ms
[14:44] triggering bind test:account
[14:44] CrazyCat is CrazyCat on #raspfr
[14:44] triggered bind test:account, user 0.400ms sys 0.169ms
```

After searches: the bind is triggered for each channel I'm already in (and the eggdrop too).

**Comment by crazycatdevs** [comment]
Testing the new version:

I'm already on #raspfr, #zeolia and #opers (and the eggdrop too), joining #test (where the eggdrop is):
```
.tcl proc ba {n u h c a} { putlog "Seen $n on $c with account $a" }
.tcl bind account - * ba
```
```
[08:36] triggering bind ba
[08:36] Seen CrazyCat on #raspfr with account CrazyCat
[08:36] triggered bind ba, user 0.821ms sys 0.320ms
[08:36] triggering bind ba
[08:36] Seen CrazyCat on #zeolia with account CrazyCat
[08:36] triggered bind ba, user 0.691ms sys 0.268ms
[08:36] triggering bind ba
[08:36] Seen CrazyCat on #opers with account CrazyCat
[08:36] triggered bind ba, user 0.682ms sys 0.265ms
```
Seems better :)

**Comment by vanosg** [comment]
Code has been updated; PR now does:
- .+account / .-account  (not just .account)
- bind activated only on an ACCOUNT (previous functionality)
- passes account information as part of userfile sharing
- broadcasts changes to the account field to other shared bots
- multiple accounts can be added to one handle, but the same account can only be added to one handle (not multiple handles)

**Comment by vanosg** [comment]
TODO: add account to Tcl getuser command?

**Comment by vanosg** [comment]
TODO: remove error condition (according to docs, didn't verify actual functionality) if extjoin/acct-notify aren't enabled for Tcl 'getaccount'

**Pull request merged**
