### PR TITLE
(Fix #424) Forbid +bot, when handle == botnetnick

### LINKED ISSUE #424: Prevent Eggdrop from adding bot with same botnet-nick as self
Example:
```
.whoami
You are -HQ@scooby.

.+bot scooby 192.168.180.136 3183  <<Edit: This is the IP of a different bot named scooby>>
Added bot 'scooby' with address [192.168.180.136]:3183/3183 and no hostmask.
You'll want to add a hostmask if this bot will ever be on any channels that I'm on.

.link scooby
Link to myself?  Oh boy, Freud would have a field day.
```

The closest thing I can think of as a use case is something perhaps to do with userfile sharing. What do we think- should we prevent the user from doing this, or no?

### PR DESCRIPTION
**Pull request by michaelortmann**
Found by: vanosg
Patch by: michaelortmann
Fixes: #424

One-line summary:
Forbid +bot, when handle == botnetnick

Additional description (if needed):

Test cases demonstrating functionality (if applicable):
Before:
```
.whoami
[17:46:05] tcl: builtin dcc call: *dcc:whoami -HQ 1 
You are -HQ@linux.
.+bot linux lummerland 13
[17:48:59] tcl: builtin dcc call: *dcc:+bot -HQ 1 linux lummerland 13
[17:48:59] #-HQ# +bot linux lummerland 13 
Added bot 'linux' with address [lummerland]:13/13 and no hostmask.
You'll want to add a hostmask if this bot will ever be on any channels that I'm on.
.whois linux
[17:49:08] tcl: builtin dcc call: *dcc:whois -HQ 1 linux
[17:49:08] #-HQ# whois linux
HANDLE                           PASS NOTES FLAGS           LAST
linux                            no       0 b               never (nowhere)
  ADDRESS: lummerland
     users: 13, bots: 13
```
After:
```
.whoami
[17:50:41] tcl: builtin dcc call: *dcc:whoami -HQ 1 
You are -HQ@linux.
[17:50:41] #-HQ# whoami
.+bot linux lummerland 13
[17:50:47] tcl: builtin dcc call: *dcc:+bot -HQ 1 linux lummerland 13
Same botnick as mine.
.whois linux
[17:51:18] tcl: builtin dcc call: *dcc:whois -HQ 1 linux
[17:51:18] #-HQ# whois linux
Can't find anyone matching that.
```

### CODE REVIEW

**Review by thommey — APPROVED** [review]

**Comment by vanosg** [comment]
build

**Review by thommey — APPROVED** [review]

**Comment by Cizzle** [comment]
Please don't block adding bots with same botnet-nick.

**Comment by vanosg** [comment]
Why?

**Comment by Cizzle** [comment]
Because I use it.

**Comment by vanosg** [comment]
To expand on Cizzle's eloquence...

   If starting a botnet and the local bot is the hub, you need to add the bot to itself, in order to propogate it for the other leaf bots to have the record after they download the userfile from the hub. 

Differently said, I add a hub bot to a leaf, connect to the hub, and download the userfile. If the hub bot isn't in that userfile, the hub bot entry disappears. (if I recall correctly)

**Pull request closed without merging**
